### ISSUE TITLE
Optimize calls based on representatives' position?

### ISSUE THREAD

**Issue by carmiendo** [5calls/5calls#68] opened 2017-01-30 19:29 UTC
In the script, we ask for the senator or representative's position on an issue.

Can we collect that data on the site to allow people to focus their calls specifically on issues where their senator or representative has not already taken the stance the caller agrees with?

**Comment by oderby** [comment] 2017-02-02 22:31
This seems related/dupe of #87?

**Comment by carmiendo** [comment] 2017-02-02 22:49
Specifically this comment in 87, yes: https://github.com/5calls/5calls/issues/87#issuecomment-276715474

**Closed** 2017-02-05 02:30 UTC
