### ISSUE TITLE
If location is off system-wide, browser geolocation never completes?

### ISSUE THREAD

**Issue by nickoneill** [5calls/5calls#149] opened 2017-02-05 03:17 UTC
From an email support ticket:

> I've been visiting daily and making my calls. 
today I tried to log on and the screen won't progress past "getting your location."

> I intentionally don't have "location" enabled on my mac. 
Please bring back the feature that allows me to enter my zip code!

**Comment by capndesign** [comment] 2017-02-05 19:28
@nickoneill Did this user mention their browser? This is a known issue with Firefox. I’ll see if I can find a workaround.

**Comment by nickoneill** [comment] 2017-02-05 19:29
No mention of browser, unfortunately

**Comment by KathyApplebaum** [comment] 2017-02-08 00:23
I just experienced the same issue.

- 64-bit Firefox 51.0.1
- OS X Sierra
- Ghostery and Ublock Origin installed.

Turning off Ublock Origin allows the "share your location" popup, but if you decline to share there's no obvious way forward (like entering a zip code)

**Comment by nickoneill** [comment] 2017-02-08 04:38
Thanks @KathyApplebaum, I think there should be a timeout here so people with blocking software installed (or those that don't want to allow location) can get to the issues relatively quickly on their first visit.

**Comment by capndesign** [comment] 2017-02-08 20:52
@nickoneill I was experimenting with a solution like that. I think I’m going to have it fall back to ipinfo.com if there is no response after 5 seconds. The problem is that the browser location function call does not return a response until a location is found. There is _no_ response when the user clicks/taps to allow browser location. This is problematic because it can easily take 5 seconds just for the geolocation (plus the time it takes a user to notice and tap the dialog).

Soooo, it probably makes sense to call IP Info after 5 seconds and replace the data if they accept the browser dialog.

Thoughts?

**Comment by nickoneill** [comment] 2017-02-08 21:03
I think that's perfect. Would much rather take a semi-decent location for a few seconds and then improve it if they accept, particularly if it happens seamlessly!

**Comment by oderby** [comment] 2017-02-13 11:16
I think this can be closed now that #184 merged, right?

**Closed** 2017-03-04 03:47 UTC
Labels: bug, frontend

**Comment by nickoneill** [comment] 2017-03-05 03:13
Yep, all good here 👍 , thanks @oderby
