### ISSUE TITLE
Location wiped out on clicking issue 

### ISSUE THREAD

**Issue by imaflamingo** [5calls/5calls#80] opened 2017-01-31 15:01 UTC
I set my location to my zip code and am able to see my representatives based on location for the most recent issues like appointing Steve Bannon to the NSC. But when I click on Jeffrey Sessions it said no location found and prompted me to enter my zip code. Tried a couple times same issue, using iPhone with safari

**Comment by ColemanCollins** [comment] 2017-01-31 20:23
Trying to reproduce — is it actually _clearing_ your location info, or telling you to set your location to see your reps while persisting the location info you put in?

That is, if you scroll up from the "set your location" link *without* hitting it, does it still show your zip? or does it show the input again; if you go from an Issue page that is showing reps correctly based on your address to one that is telling you to set your location, and then back to one you know that works without entering new address info, does your rep appear again?

I can create a similar situation with either my zip or my full address—thought it might be a split zip thing—on the AAG Yates issue right now (iOs Chrome; Mac Chrome v55), but it's not truly clearing my information, only not resolving an appropriate person to call. If I click on any of the other live issue pages, they still work fine.

**Comment by mjoyce91** [comment] 2017-01-31 23:17
Same issue. Here are the steps I'm following.

1. Enter site
2. Enter my location, click go
3. Location is saved (displays "for [my address I just entered]")
3. Click on an issue from sidebar
4. Prompt to "Set your location to find your representatives" appears
5. When I click on that, my address is wiped
6. When I enter my address and repeat, the same thing happens

**Comment by ColemanCollins** [comment] 2017-02-01 01:09
@mjoyce91 noted. Trying to clarify here — does your address ever get wiped just by _clicking on an issue_, or only when you click on the "Set your location" link? 

From some preliminary digging, what I think is going on here is twofold: 
1) there are issues being returned based on a successful location-based call with no contacts at all (no idea what's going on here; don't have enough Go experience to effectively debug), and 
2) the front-end fallback is pretty naive, only providing "set your location" (implying that you haven't yet done that, or that the app has cleared it somehow, even if you still have a location set) or "call these contacts" as the two options, when in reality there's the third option of "you have set your location and for some reason that doesn't give us any contacts for this issue." 

From a front-end perspective, this issue can probably also encompass #63 (and maybe #64 too)? — both of those seem to be the byproduct of successfully making a request to the backend against a location and getting a response back that is incomplete or empty, and the solution is a more robust fallback that takes the additional states into account. (w/r/t #64 there's already the returned concept of a splitDistrict — may be as simple as popping in a notice that refining location might be a solution when this flag is true.)

**Comment by imaflamingo** [comment] 2017-02-01 01:10
I am not able to reproduce the issue, they are all working for me now. Before some of the issues were loading the representative info and some asked me to set my location but I can't answer your question since it's working now

**Comment by mjoyce91** [comment] 2017-02-02 15:32
Seems to be working for me now

**Comment by nickoneill** [comment] 2017-02-02 15:46
Good here? Reopen if it comes up again

**Closed by nickoneill** 2017-02-02 15:46 UTC
